import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Topsection from '../components/Topsection'
import Pillars from '../components/Pillars'
import Pastprojects from '../components/Pastprojects'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'
import LearnMoreButton from '../components/LearnMoreButton'
import Link from "next/link";
import { useRouter } from "next/router";


export default function Home()
{
  return(
    <div className= {styles.container}>
      <Navbar/>
      <div className={ styles.topSectionContainer }>
        <div>
          <h1 className={ styles.homePageTitle }>Software For<br/>Social<br/>Good</h1>
          <h2 className={ styles.homePageSubTitle }> We connect VCU students with outer<br/>communities through projects that brings<br/>social impact.</h2>
          <LearnMoreButton/>
        </div>
        <div>
          <Image src="/topSecImg.svg" width="719" height="597" placeholder="empty" />
        </div>
      </div>
      <Footer/>
    </div>
    
  )
}







// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to Software for Social Good!
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
